#!/bin/sh
# Render the Homebrew formula for one release from its SHA256SUMS.txt.
#
#   packaging/homebrew/render-formula.sh v0.5.0 SHA256SUMS.txt > Formula/ohmygpu.rb
#
# The release workflow runs this after publishing and pushes the result to the
# ohmygpu/homebrew-tap repository (job `homebrew`); platforms whose archive is
# missing from the release (optional CI targets) are simply left out.
set -eu

[ $# -eq 2 ] || { echo "usage: $0 <tag> <SHA256SUMS.txt>" >&2; exit 2; }
tag="$1"
sums="$2"
base="https://github.com/ohmygpu/ohmygpu/releases/download/${tag}"

sha() { awk -v f="ohmygpu-$1.tar.gz" '$2 == f || $2 == "*" f { print $1 }' "$sums"; }

block() { # block <indent> <target>
    s=$(sha "$2")
    [ -n "$s" ] || return 0
    printf '%s  url "%s/ohmygpu-%s.tar.gz"\n' "$1" "$base" "$2"
    printf '%s  sha256 "%s"\n' "$1" "$s"
}

mac_arm=$(sha aarch64-apple-darwin)
mac_x64=$(sha x86_64-apple-darwin)
linux_x64=$(sha x86_64-unknown-linux-gnu)
linux_arm=$(sha aarch64-unknown-linux-gnu)
[ -n "$mac_arm$mac_x64$linux_x64$linux_arm" ] || { echo "no ohmygpu archives listed in $sums" >&2; exit 1; }

cat <<RUBY
# Generated by packaging/homebrew/render-formula.sh in ohmygpu/ohmygpu — do not edit by hand.
class Ohmygpu < Formula
  desc "Headless local AI runtime: OpenAI-compatible APIs over llama.cpp and whisper.cpp"
  homepage "https://github.com/ohmygpu/ohmygpu"
  license "Apache-2.0"

RUBY
if [ -n "$mac_arm$mac_x64" ]; then
    echo "  on_macos do"
    if [ -n "$mac_arm" ]; then echo "    on_arm do"; block "    " aarch64-apple-darwin; echo "    end"; fi
    if [ -n "$mac_x64" ]; then echo "    on_intel do"; block "    " x86_64-apple-darwin; echo "    end"; fi
    echo "  end"
fi
if [ -n "$linux_x64$linux_arm" ]; then
    [ -n "$mac_arm$mac_x64" ] && echo
    echo "  on_linux do"
    if [ -n "$linux_arm" ]; then echo "    on_arm do"; block "    " aarch64-unknown-linux-gnu; echo "    end"; fi
    if [ -n "$linux_x64" ]; then echo "    on_intel do"; block "    " x86_64-unknown-linux-gnu; echo "    end"; fi
    echo "  end"
fi
cat <<'RUBY'

  def install
    bin.install "ohmygpu-runtime", "ohmygpu"
    bin.install_symlink "ohmygpu" => "omg"
  end

  def caveats
    <<~EOS
      Start the runtime with `omg serve`, then `omg model pull qwen2.5-0.5b-instruct` and
      `omg run qwen2.5-0.5b-instruct`. Models and llama.cpp live in ~/.config/ohmygpu.
      Upgrade with `brew upgrade ohmygpu` (not `omg upgrade`, which is for script installs).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ohmygpu --version")
    assert_match version.to_s, shell_output("#{bin}/ohmygpu-runtime --version")
  end
end
RUBY
